### ISSUE TITLE
execution error 

### ISSUE THREAD

**Issue by W-venemum** [Noko7/Spotify-Downloader#2]
I'm unable to run the code even after importing selenium.webdriver & dotenv, and I was also not able to run the "pip install -r requirements.txt" command on cmd. And then it showed me to add environment variables but after adding it still didn't work. 
![Screenshot (21)](https://github.com/Noko7/Spotify-Downloader/assets/157103348/288b7982-e2b2-419e-839b-333b8d770efc)

**Comment by Noko7** [comment]
I just posted a revised version
