### ISSUE TITLE
Spotify OAuth setup error

### ISSUE THREAD

**Issue by student2514** [Noko7/Spotify-Downloader#3]
For me it showing Spotify OAuth setup error: No client_id. Pass it or set a SPOTIPY_CLIENT_ID environment variable. could you help me
![Untitled](https://github.com/Noko7/Spotify-Downloader/assets/113430772/42cd30d7-3d99-45b1-91b3-664fe15b8f50)

**Comment by Noko7** [comment]
It looks like you forgot to create the .env file with your client id and secret.
