### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Gagans90** [Noko7/Spotify-Downloader#5]
I'm Getting this problem
![main py - Spotify-Downloader-main - Visual Studio Code 04-08-2024 1 47 50 PM](https://github.com/user-attachments/assets/d90b4c35-d155-4831-ba32-643fb0f61c13)

**Comment by Noko7** [comment]
Run the command 'python pip install requests'

**Comment by Noko7** [comment]
Also make sure you ran the command 'python pip install -r requirements.txt'

**Comment by Gagans90** [comment]
> python pip install requests
In the Vs code ?

**Comment by Noko7** [comment]
Yep. In the terminal in vs code

**Comment by Gagans90** [comment]
![main py - Spotify-Downloader-main - Visual Studio Code 04-08-2024 1 53 41 PM](https://github.com/user-attachments/assets/ed715936-3739-4f49-adf8-094d16762fca)

**Comment by Noko7** [comment]
Just run 'pip install requests' without the python in front

**Comment by Gagans90** [comment]
![Captures 04-08-2024 1 58 43 PM](https://github.com/user-attachments/assets/bfdb330e-22ab-456f-b3f9-3638f0a1d79f)
Now What ?

**Comment by Noko7** [comment]
Run the script again

**Comment by Gagans90** [comment]
no its not working

**Comment by Gagans90** [comment]
Same error

**Comment by Noko7** [comment]
Make sure you installed requests and all other required packages. If you need more step by step walkthrough use chatgpt and paste the script with the error messages and it will tell you the commands exactly.

**Comment by Gagans90** [comment]
Okay, I will try that. Thanks

**Comment by Gagans90** [comment]
Thanks it worked

**Comment by Gagans90** [comment]
![image](https://github.com/user-attachments/assets/289570e1-54d1-4533-b548-c608ab32b804)
It's Not responding

**Comment by Noko7** [comment]
Close it and retry

**Comment by Gagans90** [comment]
Done that it's not working

**Comment by Gagans90** [comment]
![(136) Unbelievable Secret to Getting Free Spotify with Python! - YouTube - Brave 04-08-2024 2 23 38 PM](https://github.com/user-attachments/assets/bdbb2f43-18f8-4acb-bff5-f4a8300dee18)
Keep getting this error

**Comment by Noko7** [comment]
Ok. I will update the code tomorrow to fix that. Check back in then.

**Comment by Gagans90** [comment]
okay

**Comment by Gagans90** [comment]
Can you notify me when the code is updated

**Comment by LeCurateur** [comment]
Having the same issue, just completed the installation. I guess I will wait for the updated code. Thanks!

**Comment by Gagans90** [comment]
How much time dude

**Comment by eugene4545** [comment]
Hello, @Noko7  It’s been a while since you said you’d update the code to fix the bug, are you still planning to do that? I’d really appreciate an update

**Comment by NudeMilk** [comment]
![image](https://github.com/user-attachments/assets/6c255c11-7b4b-4aae-aaa7-aa1503b5a4c6)
Hi, i m having the same problem. Keep getting the "Bad Request " problem. The only change i made was to modify the requirements.txt file cause it couldn't find the spotipy version that was written there so i changed it to the 2.24.0 version instead of 2.19.1 and it worked. All went well until i had to download the playlists, now it give me the "Bad Request" error with every playlist i try to download. It would be much appreciated if you could help. Thank you very much

**Comment by Noko7** [comment]
# Hi Everyone, I have updated the code I apologize for the delay. It works now! Please let me know if it works

**Comment by Noko7** [comment]
Make sure you run "pip install -r requirements.txt" before you try and run the script again

**Comment by NudeMilk** [comment]
Hi, thank you very much for updating the code but, if i may ask for your help, i still have a problem: when i run the script it start downloading the first song of the playlist and the it send in loop always the same error without downloading nothing.
I ll send a scrrenshot, Thank you very much.
![error](https://github.com/user-attachments/assets/6efdba1a-6013-4f25-8d49-f39db04eea1a)

**Comment by eugene4545** [comment]
You'll need to download ffmpeg and add the path to your environment variables...I had the same issue too

**Comment by NudeMilk** [comment]
> You'll need to download ffmpeg and add the path to your environment variables...I had the same issue too

Thank you you re a life saver, now it works!

**Comment by eugene4545** [comment]
you're welcome... and thanks @Noko7 for updating the code
